Repository team7-newsfeed-project/whats-your-music, pull requests merged in 2024-02, with the labels that each got.

#21 [feat/#20] layout 컴포넌트 임포트 등
  src/App.jsx
  src/GlobalStyle.jsx
  src/assets/defaultImage.png
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/layout/Layout.jsx
  src/components/main/Main.jsx
  src/components/main/MainPostItem.jsx
  src/pages/Detail.jsx
  src/pages/Home.jsx
  src/shared/postsDummyData.js
Labels: documentation, enhancement

#27 [feat&fix&add/#26] 로그인 link 주소 수정 및 MainPostItem 컴포넌트 추가
  src/components/layout/Layout.jsx
  src/components/main/Header.jsx
  src/components/main/Main.jsx
  src/components/main/MainPostItem.jsx
  src/shared/postsDummyData.js
  yarn.lock
Labels: documentation, enhancement

#35 [feat/#34] Header의 카테고리메뉴 선택 시 해당리스트항목 뜨게 하기 구현 (dummydata사용)
  src/assets/thumbnailExImg.png
  src/components/main/Header.jsx
  src/components/main/Main.jsx
  src/components/main/MainPostItem.jsx
  src/pages/Home.jsx
  src/shared/postsDummyData.js
Labels: documentation, enhancement

#38 Feat/login register
  src/App.jsx
  src/database/FirebaseAPI.js
  src/database/firebase.js
  src/pages/LogIn.jsx
  src/pages/Register.jsx
  src/store/config/configStore.js
  src/store/modules/userAccount.js
  yarn.lock
Labels: documentation, enhancement

#41 [Feat/#40] 버튼 컴포넌트 생성 및 store, 리 추가, myPage에 필요한 main영역 컴포넌트 추가
  src/App.jsx
  src/components/common/Button.jsx
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/styles/ButtonStyled.jsx
  src/components/styles/MypageStyle.jsx
  src/components/styles/Profile.jsx
  src/database/FirebaseAPI.js
  src/database/firebase.js
  src/pages/MyPage.jsx
  src/store/config/configStore.js
  src/store/modules/userImage.js
Labels: documentation, enhancement

#49 [Feat/#47] 이미지 업로드 완성 및 userImage .js 리듀서 내용 추가
  src/components/main/ProfileImage.jsx
  src/pages/MyPage.jsx
  src/store/modules/userImage.js
Labels: bug, documentation, enhancement

#54 [Feat/#53] 유저 고유번호 uid 기준, 로그인 상태 변화 저장 리듀서 생성
  src/components/main/ProfileImage.jsx
  src/components/styles/ProfileStyle.jsx
  src/pages/MyPage.jsx
  src/store/config/configStore.js
  src/store/modules/userLogin.js
Labels: documentation, enhancement

#61 [feat/#60] PostForm 글 등록 구현
  src/components/common/CategoryDropdown.jsx
  src/pages/PostForm.jsx
Labels: documentation, enhancement

#63 [feat/#62] 메인페이지 게시글아이템에서 유튜브 영상 iframe으로 구현, 헤더 유저로그인상태따라 다르게 구현 완료
  src/assets/whatsyourmusicLogo.png
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/main/RecommendListMain.jsx
  src/components/main/RecommendPostItem.jsx
  src/components/main/RecommendPostVideoSection.jsx
  src/shared/postsDummyData.js
  src/store/modules/posts.js
Labels: documentation, enhancement

#67 Feat/login register
  src/App.jsx
  src/database/FirebaseAPI.js
  src/pages/LogIn.jsx
  src/pages/Register.jsx
  src/store/modules/userAccount.js
Labels: documentation, enhancement

#84 [style & update/#81] 폰트전체적용, 전반적 css 스타일링, 로고이미지변경, 글 등록시 date키의 value값 ISO String으로 변경 등
  package.json
  src/GlobalStyle.jsx
  src/assets/whatsyourmusic_logo.png
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/main/RecommendListMain.jsx
  src/components/main/RecommendPostItem.jsx
  src/components/main/RecommendPostVideoSection.jsx
  src/components/styles/LayoutStyle.jsx
  src/pages/Detail.jsx
  src/pages/LogIn.jsx
  src/pages/MyPage.jsx
  src/pages/PostForm.jsx
  src/pages/Register.jsx
  src/store/modules/posts.js
  yarn.lock
Labels: documentation, enhancement

#91 [Style/#86] 마이페이지 css
  src/GlobalStyle.jsx
  src/components/main/MyRecommend.jsx
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/main/RecommendPostVideoSection.jsx
  src/components/styles/ButtonStyled.jsx
  src/components/styles/MypageStyle.jsx
  src/components/styles/ProfileContentsSt.jsx
  src/components/styles/ProfileImageSt.jsx
  src/pages/Detail.jsx
  src/pages/MyPage.jsx
  src/store/modules/userAccount.js
  src/store/modules/userContents.js
  src/store/modules/userImage.js
  src/store/modules/userRecommend.js
Labels: documentation, enhancement

#93 [style&feat/#92] 로그인,회원가입페이지 wrapper수정, button 위주로 스타일링 수정 (아직미완성)
  src/GlobalStyle.jsx
  src/assets/logoImage.png
  src/assets/thumbnailExImg.png
  src/components/Footer/Footer.jsx
  src/components/Header/MainHeader.jsx
  src/components/styles/ButtonStyled.jsx
  src/components/styles/MypageStyle.jsx
  src/pages/Home.jsx
  src/pages/LogIn.jsx
  src/pages/MyPage.jsx
  src/pages/PostForm.jsx
  src/pages/Register.jsx
  src/store/modules/posts.js
Labels: documentation, enhancement

#104 [Style] - 마이페이지 내가 추천하는 음악 css
  src/components/main/MyRecommend.jsx
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/styles/ButtonStyled.jsx
  src/components/styles/MyRecommendStyle.jsx
  src/components/styles/MypageStyle.jsx
  src/components/styles/ProfileContentsSt.jsx
  src/components/styles/ProfileContentsStyle.jsx
  src/components/styles/ProfileImageSt.jsx
  src/components/styles/ProfileImageStyle.jsx
  src/pages/MyPage.jsx
Labels: documentation

#108 [Style/#107] 마이페이지 css 완성
  src/components/main/MyRecommend.jsx
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/styles/MyRecommendStyle.jsx
  src/pages/Detail.jsx
Labels: documentation

#109 [Style/#108] 마이페이지 찐찐 css 등록 버튼 수정
  src/components/styles/ProfileImageStyle.jsx
Labels: documentation

#115 [Refactor] - ProfileImage 주석 및 콘솔 지우기
  src/components/main/MyRecommend.jsx
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/styles/ProfileImageStyle.jsx
  src/pages/MyPage.jsx
Labels: Chore

#117 [Chore] - 마이페이지에 폰트 적용, reset.css에 직접 font-family로 적용시켜줌
  src/GlobalStyle.jsx
Labels: Chore

#120 [Fix] - 디폴트 이미지 다시 뜨게 하고, ProfileContents 폰트 크기 수정, 로그아웃 시 질문 추가
  src/components/main/ProfileContents.jsx
  src/components/main/ProfileImage.jsx
  src/components/styles/ProfileContentsStyle.jsx
Labels: bug, documentation, enhancement

#122 [Chore] pull 당기고 다시 풀리퀘
  src/components/main/ProfileImage.jsx
Labels: Chore

#125 [Fix/#123] 섬네일 버그해결, css 정리
  src/components/main/MyRecommend.jsx
  src/components/main/ProfileImage.jsx
  src/components/main/RecommendPostVideoSection.jsx
  src/components/styles/MyRecommendStyle.jsx
  src/pages/MyPage.jsx
Labels: bug, documentation, enhancement
